import { UserProfile, Gift, CreditPackage, Reel, SubscriptionPlan, Achievement } from './types';

// Placeholder avatars for user profile customization
export const PLACEHOLDER_AVATARS: string[] = [
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1887&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1887&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1887&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1887&auto=format&fit=crop',
];


// Mock profiles for the discovery feed
export const PROFILES: UserProfile[] = [
    {
        id: 'prof_1',
        name: 'Sophia',
        age: 28,
        imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1887&auto=format&fit=crop',
        occupation: 'Graphic Designer',
        bio: "Creative soul who loves painting, hiking, and finding hidden cafes. Looking for someone to share adventures and quiet moments with. Fluent in sarcasm and coffee.",
        interests: ['Art', 'Photography', 'Indie Music'],
        hobbies: ['Painting', 'Hiking', 'Trying new recipes'],
        country: 'USA',
        lastSeen: new Date(Date.now() - 1000 * 60 * 3).toISOString(), // 3 mins ago
        icebreakers: [
            "What's the last thing that made you laugh?",
            "Best hidden cafe you've discovered?",
            "Dream travel destination and why?"
        ],
    },
    {
        id: 'prof_2',
        name: 'Liam',
        age: 31,
        imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1887&auto=format&fit=crop',
        occupation: 'Software Engineer',
        bio: "Building cool things by day, exploring the city by night. I'm a big fan of live music, spicy food, and board games. Let's build a connection, one line of code at a time.",
        interests: ['Technology', 'Live Music', 'Cooking'],
        hobbies: ['Board Games', 'Rock Climbing', 'Podcasts'],
        country: 'Canada',
        lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(), // 25 hours ago
        icebreakers: [
            "Favorite board game to play on a rainy day?",
            "Best concert you've ever been to?",
            "What's your go-to spicy dish?"
        ],
    },
    {
        id: 'prof_3',
        name: 'Isabella',
        age: 26,
        imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop',
        occupation: 'Chef',
        bio: "My love language is food. I believe every meal should be an experience. When I'm not in the kitchen, I'm probably tending to my garden or planning my next trip.",
        interests: ['Gastronomy', 'Travel', 'Gardening'],
        hobbies: ['Baking', 'Yoga', 'Documentaries'],
        country: 'Italy',
        lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4 hours ago
        icebreakers: [
            "What's your comfort food?",
            "Most memorable meal you've ever had?",
            "Coffee or tea - and how do you take it?"
        ],
    },
     {
        id: 'prof_4',
        name: 'Noah',
        age: 30,
        imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1887&auto=format&fit=crop',
        occupation: 'Veterinarian',
        bio: "Dog dad, avid reader, and aspiring marathon runner. I can often be found at the park with my golden retriever, Leo. Looking for someone who doesn't mind a little dog hair.",
        interests: ['Animals', 'Running', 'Reading'],
        hobbies: ['Volunteering', 'Playing Guitar', 'Camping'],
        country: 'Australia',
        lastSeen: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
        icebreakers: [
            "Dog person or cat person?",
            "Last book that left you thinking?",
            "Favorite camping spot you've discovered?"
        ],
    }
];

// Available gifts in the application
export const GIFTS: Gift[] = [
    { id: 'gift_1', name: 'Rose', icon: '🌹', cost: 50 },
    { id: 'gift_2', name: 'Teddy Bear', icon: '🧸', cost: 150 },
    { id: 'gift_3', name: 'Chocolate Box', icon: '🍫', cost: 75 },
    { id: 'gift_4', name: 'Champagne', icon: '🍾', cost: 200 },
    { id: 'gift_5', name: 'Diamond Ring', icon: '💍', cost: 500 },
    { id: 'gift_6', name: 'Bouquet', icon: '💐', cost: 100 },
    { id: 'gift_7', name: 'Heart', icon: '❤️', cost: 30 },
    { id: 'gift_8', name: 'Star', icon: '⭐', cost: 120 },
];

// Credit packages available for purchase
export const CREDIT_PACKAGES: CreditPackage[] = [
  // USD
  { id: 'usd_1', credits: 100, price: 0.99, currency: 'USD' },
  { id: 'usd_2', credits: 550, price: 4.99, currency: 'USD' },
  { id: 'usd_3', credits: 1200, price: 9.99, currency: 'USD' },
  // EUR
  { id: 'eur_1', credits: 100, price: 0.99, currency: 'EUR' },
  { id: 'eur_2', credits: 550, price: 4.99, currency: 'EUR' },
  { id: 'eur_3', credits: 1200, price: 9.99, currency: 'EUR' },
  // GBP
  { id: 'gbp_1', credits: 100, price: 0.89, currency: 'GBP' },
  { id: 'gbp_2', credits: 550, price: 4.49, currency: 'GBP' },
  { id: 'gbp_3', credits: 1200, price: 8.99, currency: 'GBP' },
  // CZK
  { id: 'czk_1', credits: 100, price: 25, currency: 'CZK' },
  { id: 'czk_2', credits: 550, price: 125, currency: 'CZK' },
  { id: 'czk_3', credits: 1200, price: 250, currency: 'CZK' },
  // PLN
  { id: 'pln_1', credits: 100, price: 4.49, currency: 'PLN' },
  { id: 'pln_2', credits: 550, price: 22, currency: 'PLN' },
  { id: 'pln_3', credits: 1200, price: 45, currency: 'PLN' },
  // CHF
  { id: 'chf_1', credits: 100, price: 0.99, currency: 'CHF' },
  { id: 'chf_2', credits: 550, price: 4.99, currency: 'CHF' },
  { id: 'chf_3', credits: 1200, price: 9.99, currency: 'CHF' },
];

// Subscription plans (Premium memberships)
export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  // USD Plans
  {
    id: 'usd_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 9.99,
    currency: 'USD',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'usd_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 19.99,
    currency: 'USD',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'usd_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 34.99,
    currency: 'USD',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
  // EUR Plans
  {
    id: 'eur_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 9.99,
    currency: 'EUR',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'eur_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 19.99,
    currency: 'EUR',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'eur_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 34.99,
    currency: 'EUR',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
  // GBP Plans
  {
    id: 'gbp_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 8.99,
    currency: 'GBP',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'gbp_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 17.99,
    currency: 'GBP',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'gbp_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 29.99,
    currency: 'GBP',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
  // CZK Plans
  {
    id: 'czk_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 249,
    currency: 'CZK',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'czk_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 499,
    currency: 'CZK',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'czk_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 849,
    currency: 'CZK',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
  // PLN Plans
  {
    id: 'pln_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 45,
    currency: 'PLN',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'pln_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 89,
    currency: 'PLN',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'pln_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 149,
    currency: 'PLN',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
  // CHF Plans
  {
    id: 'chf_basic_monthly',
    tier: 'basic',
    name: 'Basic',
    price: 9.99,
    currency: 'CHF',
    duration: 'monthly',
    features: [
      '5 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '1 free Boost per month',
    ],
  },
  {
    id: 'chf_premium_monthly',
    tier: 'premium',
    name: 'Premium',
    price: 19.99,
    currency: 'CHF',
    duration: 'monthly',
    features: [
      '10 Super Likes per day',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '2 free Boosts per month',
      'Read receipts',
      'Priority profile visibility',
      'Advanced filters',
    ],
  },
  {
    id: 'chf_vip_monthly',
    tier: 'vip',
    name: 'VIP',
    price: 34.99,
    currency: 'CHF',
    duration: 'monthly',
    features: [
      'Unlimited Super Likes',
      'See who liked you',
      'Unlimited rewinds',
      'Ad-free experience',
      '5 free Boosts per month',
      'Read receipts',
      'Top profile placement',
      'Advanced filters',
      'Verified badge',
      'Monthly credit bonus (500)',
      'Exclusive VIP support',
    ],
  },
];

// Mock Reels data
export const REELS: Reel[] = [
    {
        id: 'reel_1',
        videoUrl: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4',
        description: 'Just enjoying the beautiful scenery on my hike today! 🌲☀️ #nature #hiking',
        userProfile: PROFILES[0],
    },
    {
        id: 'reel_2',
        videoUrl: 'https://test-videos.co.uk/vids/jellyfish/mp4/h264/360/Jellyfish_360_10s_1MB.mp4',
        description: 'My latest coding project is finally coming to life! #coding #developer',
        userProfile: PROFILES[1],
    },
    {
        id: 'reel_3',
        videoUrl: 'https://test-videos.co.uk/vids/sintel/mp4/h264/360/Sintel_360_10s_1MB.mp4',
        description: 'Baking up a storm this weekend. 🥐 #baking #foodie',
        userProfile: PROFILES[2],
    },
];

// Achievements and badges
export const ACHIEVEMENTS: Achievement[] = [
    // Streak Achievements
    {
        id: 'streak_3',
        name: '3-Day Streak',
        description: 'Log in for 3 consecutive days',
        icon: '🔥',
        category: 'streak',
        target: 3,
    },
    {
        id: 'streak_7',
        name: 'Week Warrior',
        description: 'Maintain a 7-day login streak',
        icon: '⚡',
        category: 'streak',
        target: 7,
    },
    {
        id: 'streak_30',
        name: 'Monthly Master',
        description: 'Achieve a 30-day login streak',
        icon: '👑',
        category: 'streak',
        target: 30,
    },
    {
        id: 'streak_100',
        name: 'Century Club',
        description: 'Reach a 100-day login streak',
        icon: '💯',
        category: 'streak',
        target: 100,
    },
    // Social Achievements
    {
        id: 'matches_10',
        name: 'Connection Starter',
        description: 'Get your first 10 matches',
        icon: '💖',
        category: 'social',
        target: 10,
    },
    {
        id: 'matches_50',
        name: 'Social Butterfly',
        description: 'Reach 50 total matches',
        icon: '🦋',
        category: 'social',
        target: 50,
    },
    {
        id: 'matches_100',
        name: 'Matchmaking Pro',
        description: 'Achieve 100 matches',
        icon: '✨',
        category: 'social',
        target: 100,
    },
    // Engagement Achievements
    {
        id: 'messages_100',
        name: 'Conversationalist',
        description: 'Send 100 messages',
        icon: '💬',
        category: 'engagement',
        target: 100,
    },
    {
        id: 'messages_500',
        name: 'Chat Master',
        description: 'Send 500 messages',
        icon: '📱',
        category: 'engagement',
        target: 500,
    },
    {
        id: 'likes_50',
        name: 'Generous Heart',
        description: 'Give 50 likes',
        icon: '❤️',
        category: 'engagement',
        target: 50,
    },
    {
        id: 'gifts_10',
        name: 'Gift Giver',
        description: 'Send 10 gifts',
        icon: '🎁',
        category: 'engagement',
        target: 10,
    },
    // Special Achievements
    {
        id: 'profile_complete',
        name: 'All Set Up',
        description: 'Complete your profile with photo and bio',
        icon: '✅',
        category: 'special',
        target: 1,
    },
    {
        id: 'verified',
        name: 'Verified User',
        description: 'Get your profile verified',
        icon: '🔵',
        category: 'special',
        target: 1,
    },
    {
        id: 'early_adopter',
        name: 'Early Adopter',
        description: 'Join in the first month of launch',
        icon: '🚀',
        category: 'special',
        target: 1,
    },
];
